[env:due]
platform = atmelsam
board = due
framework = arduino

monitor_speed = 115200
build_flags =
    -std=c++14
    -Wall

[env:native]
platform = native
build_flags =
    -std=c++14
    -Wall
    -I include
    -I test/mocks
test_build_src = yes
